### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by souraOP** [iampranavdhar/Library-Management-System-MERN#2]
Hey dude I have tried doing the steps mentioned in the Readme file.
But after creating the .env file inside frontend folder then running yarn start gives me some error 
![Screenshot 2023-07-20 at 5 26 36 AM](https://github.com/iampranavdhar/Library-Management-System-MERN/assets/83086483/dd88a49c-c7e9-4d7b-a356-46f2729a2c8f)
 Please help me resolve the issue

**Comment by iampranavdhar** [comment]
I am assuming you are using Node v20.2.0 can you try the same by degrading Node to 16

**Comment by souraOP** [comment]
🤡
